AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'aws-ssm-parameter-store-ecs-updater-deployer

  '
Globals:
  Function:
    Timeout: 5
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Parameter-Store-ECS-Updater-and-Deployer
    Description: 'Parameter Store values are read on task creation and subsequent
      updates to parameters require a redeploy of ECS tasks. This serverless application
      facilitates propagating parameter updates via Cloudwatch Events to a function,
      that will redeploy ECS tasks.

      '
    Author: Lars Fronius
    SpdxLicenseId: MIT
    LicenseUrl: s3://aws-ssm-parameter-store-ecs-updater-deployer/7ae2be7fb1637141840314b51970a9f7
    ReadmeUrl: s3://aws-ssm-parameter-store-ecs-updater-deployer/2927d989709a72172a97b212b1d82da5
    Labels:
    - parameterstore
    - ssm
    - ecs
    - update
    - deploy
    - parameter
    HomePageUrl: https://github.com/LarsFronius/aws-ssm-parameter-store-ecs-updater-deployer
    SemanticVersion: 0.1.3
    SourceCodeUrl: https://github.com/LarsFronius/aws-ssm-parameter-store-ecs-updater-deployer
Resources:
  ParameterStoreECSUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-ssm-parameter-store-ecs-updater-deployer/parameter-store-ecs-updater-deployer.zip
      Handler: parameter-store-ecs-updater-deployer
      Runtime: go1.x
      Events:
        CatchAll:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
              - Parameter Store Change
              source:
              - aws.ssm
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - ec2:UpdateService
          - ssm:ListTagsForResource
          - ssm:GetParameters
          Resource: '*'
Outputs:
  ParameterStoreECSUpdateFunction:
    Description: Parameter Store ECS Update Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ParameterStoreECSUpdateFunction
      - Arn
  ParameterStoreECSUpdateFunctionFunctionIamRole:
    Description: Implicit IAM Role created for Parameter Store ECS Update Lambda Function
    Value:
      Fn::GetAtt:
      - ParameterStoreECSUpdateFunctionRole
      - Arn
