AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-ssm-parameter-store-ecs-updater-deployer

Globals:
  Function:
    Timeout: 5

Resources:
  ParameterStoreECSUpdateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: s3://aws-ssm-parameter-store-ecs-updater-deployer/parameter-store-ecs-updater-deployer.zip
      Handler: parameter-store-ecs-updater-deployer
      Runtime: go1.x
      Events:
        CatchAll:
          Type: CloudWatchEvent
          Properties:
              Pattern:
                detail-type:
                  - Parameter Store Change
                source:
                  - aws.ssm

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ParameterStoreECSUpdateFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt ParameterStoreECSUpdateFunction.Arn
  ParameterStoreECSUpdateFunctionFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ParameterStoreECSUpdateFunctionRole.Arn
